[package]
name = "kclip-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
futures-util.workspace = true
getrandom.workspace = true
kclip-config = { path = "../kclip-config" }
kclip-crypto = { path = "../kclip-crypto" }
kclip-protocol = { path = "../kclip-protocol" }
kclip-storage = { path = "../kclip-storage" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
snow.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
