PACKAGE_NAME="kclip"
PACKAGE_VERSION="0.1"
MAKE[0]="make KDIR=${kernel_source_dir} kmod"
CLEAN[0]="make KDIR=${kernel_source_dir} clean"
BUILT_MODULE_NAME[0]="kclip"
DEST_MODULE_LOCATION[0]="/kernel/extra"
AUTOINSTALL="yes"
